name: Build Golang App
run-name: Building Golang App for 3 Major Platform
on: [push]
jobs:
  Build-App-Golang:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Build app for windows amd64
        run: GOOS=windows GOARCH=amd64 go build -o playground_windows_amd64.exe .
      - name: Build app for linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o playground_linux_amd64 .
      - name: Build app for linux arm64
        run: GOOS=linux GOARCH=arm64 go build -o playground_linux_arm64 .
      - name: Build app for darwin arm64
        run: GOOS=darwin GOARCH=arm64 go build -o playground_darwin_arm64 .
      - run: ls -lah
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: programs
      #     path: ./playground_*
